collections:
  articles:
    output: true
    permalink: /article/:slug
  contributors:
    output: true
    permalink: /contributor/:slug
  main_pages:
    output: true
    permalink: /:slug
exclude: ["/assets/images/originals"]
kramdown:
  parse_span_html: true
sass:
  style: compressed
plugins:
  - jekyll-regex-replace
future: true
domain: classicalchronicle.org
