collections:
  articles:
    output: true
    permalink: /article/:slug
  contributors:
    output: true
    permalink: /contributor/:slug
  main_pages:
    output: true
    permalink: /:slug
exclude: ["/assets/images/originals", "mockup.ai", "coverimages.ai"]
kramdown:
  parse_span_html: true
future: true
domain: classicalchronicle.org
