defaults:
      -
        scope:
          path: ""
          type: "clubs"
        values:
          layout: "club"
      -
        scope:
          path: ""
          type: "articles"
        values:
          layout: "article"
      -
        scope:
          path: ""
          type: "contributors"
        values:
          layout: "contributor"
collections:
  articles:
    output: true
    permalink: /article/:slug
  clubs:
    output: true
    permalink: /club/:slug
  contributors:
    output: true
    permalink: /contributor/:slug
  main_pages:
    output: true
    permalink: /:slug
exclude: ["/assets/images/originals"]
kramdown:
  parse_span_html: true
sass:
  style: compressed
plugins:
  - jekyll-regex-replace
future: true
domain: classicalchronicle.org
